services:
  quiz-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051" 
    depends_on:
      - quiz_postgres
    networks:
      - quiz-network

  quiz_postgres:
      container_name: postgres_container_goida
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        PGDATA: /data/postgres
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - quiz-network

volumes:
  db-data:

networks:
  quiz-network:
    driver: bridge