stages:
  - build
  - lint

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - golangci-lint run /stat_service /quiz_service /auth_service /api_gateway_service

build:
  stage: build
  image: docker/compose:latest
  script:
    - docker-compose config
    - docker-compose up -d --build
    - docker-compose ps