stages:
  - build
  - lint

variables:
  COMPOSE_PROJECT_NAME: $CI_PROJECT_NAME-$CI_PIPELINE_ID
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind


lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - golangci-lint run /stat_service /quiz_service /auth_service /api_gateway_service

build:
  stage: build
  image: docker/compose:latest
  script:
    - docker-compose config
    - docker-compose up -d --build
    - docker-compose ps