stages:
  - lint

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - cd stat_service | go mod tidy | cd ..
    - cd quiz_service | go mod tidy | cd ..
    - cd auth_service | go mod tidy | cd ..
    - cd api_gateway_service | go mod tidy | cd ..
    - golangci-lint run /stat_service /quiz_service /auth_service /api_gateway_service