stages:
  - build
  # - lint

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IPTABLES_LEGACY: 1

# lint:
#   stage: lint
#   image: golangci/golangci-lint:latest
#   allow_failure: true
#   script:
#     - golangci-lint run ./stat_service ./quiz_service ./auth_service ./api_gateway_service

build:
  # Use the official docker image.
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # # Default branch is also tagged with `latest`
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
