stages:
  - build
  - lint

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IPTABLES_LEGACY: 1

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - golangci-lint run ./stat_service ./quiz_service ./auth_service ./api_gateway_service

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker buildx create --use
  script:
    - docker buildx build --platform linux/amd64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .

