stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - cd api_gateway_service | golangci-lint run
    - cd ..
    - cd auth_Service | golangci-lint run
    - cd ..
    - cd quiz_service | golangci-lint run
    - cd ..
    - cd stat_service | golangci-lint run
    - cd ..
    - golangci-lint run ./stat_service ./quiz_service ./auth_service ./api_gateway_service

build:
  image: golang:1.24.2-alpine3.21
  stage: build
  script:
    - cd api_gateway_service | go build -o api_gateway_service cmd/main.go
    - cd ..
    - cd auth_Service | go build -o auth_Service cmd/main.go
    - cd ..
    - cd quiz_service | go build -o quiz_service cmd/quiz/main.go
    - cd ..
    - cd stat_service | go build -o stat_service cmd/app/main.go
    - cd ..
     
  
test:
  image: golang:1.24.2-alpine3.21
  stage: test
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker buildx create --use
  script:
    - cd api_gateway_service | go test ./... -coverprofile=coverage.out
    - cd ..
    - cd auth_service | go test ./... -coverprofile=coverage.out
    - cd ..
    - cd quiz_service | go test ./... -coverprofile=coverage.out
    - cd ..
    - cd stat_service | go test ./... -coverprofile=coverage.out
    - cd ..

    - docker buildx build --platform linux/amd64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .

