version: "2"
linters:
  enable:
    - revive           # Основной линтер стиля
    - errcheck         # Проверяет обработку ошибок
    - staticcheck      # Статический анализ кода
    - gosec            # Проверка безопасности
    - govet            # Официальные проверки Go
    - gocyclo          # Проверка сложности функций
    - unconvert        # Выявляет ненужные конвертации типов
    - gocritic         # Расширенные стилевые проверки
    - ineffassign      # Обнаруживает бесполезные присваивания
    - sqlclosecheck    # Проверяет закрытие SQL-объектов
    
  exclusions:
    generated: lax
    presets:
      - comments
    paths:
      - third_party$
      - builtin$
      - examples$
