version: '3.8'

services:


  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    
    networks:
      - app_network


  stat_service: 
    container_name: stat_service
    environment:
      GRPC_PORT: 50051
      
    build:
      context: ./statistics_service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - app_network
    depends_on:
      - stat_postgres

  stat_postgres:
    container_name: stat_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: "/postgres_data"
    volumes:
       - stat_postgres:/postgres_data
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  auth_service: 
    container_name: auth_service
    environment:
      GRPC_PORT: 50052
      
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    networks:
      - app_network
    depends_on:
      - auth_postgres

  auth_postgres:
    container_name: auth_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: "/postgres_data"
    volumes:
       - auth_postgres:/postgres_data
    networks:
      - app_network
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  bye_service:
    build: ./service_2
    networks:
      - app_network
    expose:
      - "8002"


volumes:
  stat_postgres:
  auth_postgres:

networks:
  app_network:
    driver: bridge