version: '3.8'

services:


  frontend_with_nginx:
    build: ./frontend_with_nginx
    ports:
      - "8080:80"

    depends_on:
      - auth_service
      - stat_service
      - quiz_service
    
    networks:
      - app_network

  api_gateway:
    build: ./api_gateway_service
    ports:
      - "8085:8085"  # Пробрасываем порт на хост для тестов
    expose:
      - "8085"
    depends_on:
      - auth_service
      - stat_service
      - quiz_service
    
    networks:
      - app_network

  stat_service: 
    container_name: stat_service
    
    environment:
      GRPC_PORT: 50051
    expose:
      - "50051"
    build:
      context: ./stat_service
      dockerfile: Dockerfile
    networks:
      - app_network
    depends_on:
      - stat_postgres

  stat_postgres:
    container_name: stat_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
       - stat_postgres:/var/lib/postgresql/data
    
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  auth_service: 
    container_name: auth_service
    environment:
      GRPC_PORT: 50052
    
    expose:
      - "50052"        
      
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    
    networks:
      - app_network
    depends_on:
      auth_postgres:
        condition: service_healthy


  auth_postgres:
    container_name: auth_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05042007PULlup!
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
       - auth_postgres:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis_container:
    container_name: redis_container
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app_network

  quiz_service:
    build: ./quiz_service
    
    environment:
      GRPC_PORT: 50053
    expose:
      - "50053"              # gRPC порт
    networks:
      - app_network
    depends_on:
      - quiz_postgres

  quiz_postgres:
    container_name: quiz_postgres
    image: postgres:15
   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
       - quiz_postgres:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


volumes:
  stat_postgres:
    name: stat_postgres_data
  auth_postgres:
    name: auth_postgres_data
  quiz_postgres:
    name: quiz_postgres_data
  redis_data:


networks:
  app_network:
    driver: bridge
