version: '3.8'

services:


  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - greet_service
      - bye_service
    networks:
      - app_network


  stat_service: 
    container_name: stat_service
    environment:
      GRPC_PORT: 50051
      HTTP_PORT: 8080
    build:
      context: ./statistics_service
      dockerfile: Dockerfile
    ports:
      - "50051:50052"
      - "8080:8081"
    depends_on:
      - stat_postgres

  stat_postgres:
    container_name: statistics_db
    image: "postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: "/postgres_data"
    volumes:
       - postgres:/postgres_data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  auth_service: 
    container_name: stat_service
    environment:
      GRPC_PORT: 50051
      HTTP_PORT: 8080
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "50051:50052"
      - "8080:8081"
    depends_on:
      - postgres

  bye_service:
    build: ./service_2
    networks:
      - app_network
    expose:
      - "8002"



networks:
  app_network:
    driver: bridge