grpcPort: 50051

jwt:
  secret: secret
  token_ttl: 24h

db:
  host: postgres
  port: 5432
  username: postgres
  password: 05042007PULlup!
  name: postgres

redis:
  host: redis
  port: 6379
  password: ""
  db: 0