grpcPort: 50052

jwt:
  secret: secret
  token_ttl: 24h

db:
  host: auth_postgres
  port: 5432
  username: postgres
  password: 05042007PULlup!
  name: postgres

redis:
  host: redis_container
  port: 6379
  password: ""
  db: 0