GRPC_PORT: 50051 # Порт для подключения по gRPC
HTTP_PORT: 8080  # Порт для HTTP прокси

HOST: "127.0.0.1"

POSTGRES:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: "postgres"
  POSTGRES_HOST: "stat_postgres"
  POSTGRES_PORT: 5432
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 1


