services:
  stat_service: 
    container_name: stat_service
    environment:
      GRPC_PORT: 50051
      HTTP_PORT: 8080
    build:
      context: .
      dockerfile: ./Dockerfile
    
    depends_on:
      - postgres
  postgres:
    container_name: statistics_db
    image: "postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: "/postgres_data"
    volumes:
       - postgres:/postgres_data
    ports:
      - "5432:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres:

  